language: go
go:
  - "1.15.2"
go_import_path: github.com/improbable-eng/grpc-web
addons:
  hosts:
    # These must match the hosts defined in test/hosts-config.ts
    - testhost
    - corshost
env:
  global:
    - PROTOTOOL_VER=1.7.0
    # SAUCELABS environment variables
    - secure: p77sHlOl1syHdrZW7A7Y1ogjQExOGvJz/6nUTkXTwzpC+G0E2UkVXGWzpxHeNogK08IX5mAW1/3Pd7INGp1kexnzSUpSZgYPU7+UQq7oFHmzmxALXOaj7swHvIcPZ5UE4Ci9s4heXEykBshxiGCWIToAWv235c5AQKlcw/vcc9Sn/S41T3TopyofTJ3MPB3HveaMm4BbSA4DCAtCD81KYhHKXr6bUOCv/OXzORO85Y6UuRWoc20jejuzYzM8cfxEta69NcCrxcJIotXgJRi5bOWE9i8gJlY7hnnrjzz2zlJ/h/qDUpl6lDT6tlcV5ibGqB7c0SSRsOTcwXMA/lXs/dueAaqxOVGhuDEhrIQ0hQanfxhGYp51TNV2g9nr3stgS/ihqjOKG63uTfxj54RYzCg3Ldk2pEF8lDsDwqX7zjrkWB/tJurhk9D8tW8kE4J/OsR1H6+VuKMMcqPUqo900Cm0rc3y23gaMbu40wPYcZt1KDzNS0++CQLim9YtgaRD93Ey1C8gfwmH25kKK8Y+U6C2DavDVkmctoHDrkkuLQj9y/hoOKBimpqNGDwPYJmHWkfzd1PhitaSX/KfEa2n2HF7uycnD/48jGBHBA00ZNYTlmpqWhga1QKWD4c64zYHiA+Fp6xat7ZJS47+pSZemC9AC6uGGGd6//jP7ouyelQ=
    - secure: Hx1rxGnxB0NSWLmxqi7d58fzbmuyGLFDAj5BNTKfvlSTrkRSsWB6JYdfi0NQ8Jg5R+JiAx/J5OxZ6+N57D1H6Ky7C7e7yBHrqxw3g/Y8ayqfCofIWRhcFF2hlz8Xw/T9sabzlFS/Pilobk9D37YzIXppKRmfLktvBlk4vj0lhaE9RDTRSBgS2eTQ6yhSF+i7umdHxoSHeTQSvgm6f08dzulGpXzqr+is9VJ+fKdQ907O6E9AS7dMv4cnGfSWJLXybfj2Gj01ZzfAgUSSX3Jr+AKWHTUnb87OE8KxR6isH1oplmtJXIiUII//Olufigj+zxB6td/Yq0JTAazKJVraLWB09Dx87Amzgf7tk2uMAzrSLL1tfq5OH8nCQkoHPJDuboBGfPeVDw92UswW2q+4WlNxwBITt/eQ0PvCQ0hxb7BCzDgj8hKpkHkyg27G6iZfIJLHJSw2reZLK5xD4roO2/BA5fCSStXxKuALTXDsuSX6gywpIMHGpMKCBF6Toh6rjf7Q4lPiG5QH5MaPACNClWHmes2fnAikev3hn64TXtU+ohtbitMuzVS7WJsYEt23cAHidAbUQX3Y1WUvTRiapsbgM4p0DJt7JCtDxcYGY/nfpw4pWgURSfmm7aG4mr2OXJvHKk30blMoa/u/D/atsueuAqKtX9LteZ5kT4DPioM=
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get install unzip
  - sudo apt-get install moreutils
install:
  - . ./install-prototool.sh
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u github.com/robertkrimen/godocdown/godocdown
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - go install ./vendor/github.com/golang/protobuf/protoc-gen-go
  - export PATH=/home/travis/gopath/src/github.com/improbable-eng/grpc-web/protobuf/bin:$PATH
  - nvm install
  - npm install

stages:
  - lint
  - unit-test

jobs:
  include:
#    - stage: lint
#      script: ./lint-all.sh
#
#    - stage: unit-test
#      script: ./test-all.sh

    - stage: prebuild-integration-tests
      script: npm run build:integration
      workspaces:
        create:
          name: pre-built-integration-test-workspace
          paths: .

    # Node
#    - stage: nodejs-test
#      script: BROWSER=nodejs npm run test:integration:ci
#      workspaces:
#        use:
#          - pre-built-integration-test-workspace

    # Firefox
    - stage: firefox-test
      script: BROWSER=firefox80_win npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace
    - stage: firefox-test
      script: BROWSER=firefox39_win npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace
    - stage: firefox-test
      script: BROWSER=firefox38_win npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace
    - stage: firefox-test
      script: BROWSER=firefox21_win npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace

    # Chrome
    - stage: chrome-test
      script: BROWSER=chrome_85 npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace
    - stage: chrome-test
      script: BROWSER=chrome_52 npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace
    - stage: chrome-test
      script: BROWSER=chrome_43 npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace
    - stage: chrome-test
      script: BROWSER=chrome_42 npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace

    # Edge
    - stage: edge-test
      script: BROWSER=edge85_win npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace
    - stage: edge-test
      script: BROWSER=edge16_win npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace

    # Browsers that do not support trusting self-signed certs for wss:// connections have websocket tests disabled (see https://github.com/improbable-eng/grpc-web/issues/165)
    # Safari
    - stage: safari-test
      script: BROWSER=safari13_1 DISABLE_WEBSOCKET_TESTS=true npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace
    - stage: safari-test
      script: BROWSER=safari12_1 DISABLE_WEBSOCKET_TESTS=true npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace
    - stage: safari-test
      script: BROWSER=safari11_1 DISABLE_WEBSOCKET_TESTS=true npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace
    - stage: safari-test
      script: BROWSER=safari10_1 DISABLE_WEBSOCKET_TESTS=true npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace
    - stage: safari-test
      script: BROWSER=safari9_1 DISABLE_WEBSOCKET_TESTS=true npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace
    - stage: safari-test
      script: BROWSER=safari8 DISABLE_WEBSOCKET_TESTS=true npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace

    # Internet Explorer (IE)
    - stage: ie-test
      script: BROWSER=ie11_win DISABLE_WEBSOCKET_TESTS=true npm run test:integration:ci
      workspaces:
        use:
          - pre-built-integration-test-workspace

