version: 2.1

executors:
  my-executor:
    machine:
      image: ubuntu-1604:202007-01
    environment:
      PROTOTOOL_VER: 1.7.0
    working_directory: /go/src/github.com/improbable-eng/grpc-web


jobs:
  pre-build-browser-tests:
    executor: my-executor
    steps:
      - checkout
      - run: sudo apt-get install unzip
      - run:
          command: |
            set +e
            curl -O https://storage.googleapis.com/golang/go1.15.2.linux-amd64.tar.gz
            tar -xvf go1.15.2.linux-amd64.tar.gz
            sudo chown -R root:root ./go
            sudo mv go /usr/local
            echo 'export GOPATH=$HOME/go' >> $BASH_ENV
            echo 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin' >> $BASH_ENV
      - run: . ./install-prototool.sh
      - run: go get -u golang.org/x/tools/cmd/goimports
      - run: go get -u github.com/robertkrimen/godocdown/godocdown
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure
      - run: go install ./vendor/github.com/golang/protobuf/protoc-gen-go
      - run: export PATH=/home/travis/gopath/src/github.com/improbable-eng/grpc-web/protobuf/bin:$PATH
      - run:
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.33.5/install.sh | bash
            export NVM_DIR="/home/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install
            echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
            echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
      - run: npm install
      - run:
          name: Pre-Build Integration Test
          command: npm run build:integration
      - persist_to_workspace:
          root: /go/src/github.com/improbable-eng/grpc-web
          paths:
            - integration_test
  browser-tests:
    executor: my-executor
    parallelism: 4
    steps:
      - attach_workspace:
          at: /go/src/github.com/improbable-eng/grpc-web
      - run: BROWSER=nodejs npm run test:integration:ci
      - run: BROWSER=firefox80_win npm run test:integration:ci
      - run: BROWSER=firefox39_win npm run test:integration:ci
      - run: BROWSER=firefox38_win npm run test:integration:ci
      - run: BROWSER=firefox21_win npm run test:integration:ci
      - run: BROWSER=chrome_85 npm run test:integration:ci
      - run: BROWSER=chrome_52 npm run test:integration:ci
      - run: BROWSER=chrome_43 npm run test:integration:ci
      - run: BROWSER=chrome_42 npm run test:integration:ci
      - run: BROWSER=edge85_win npm run test:integration:ci
      - run: BROWSER=edge16_win npm run test:integration:ci
      - run: BROWSER=safari13_1 DISABLE_WEBSOCKET_TESTS=true npm run test:integration:ci
      - run: BROWSER=safari12_1 DISABLE_WEBSOCKET_TESTS=true npm run test:integration:ci
      - run: BROWSER=safari11_1 DISABLE_WEBSOCKET_TESTS=true npm run test:integration:ci
      - run: BROWSER=safari10_1 DISABLE_WEBSOCKET_TESTS=true npm run test:integration:ci
      - run: BROWSER=safari9_1 DISABLE_WEBSOCKET_TESTS=true npm run test:integration:ci
      - run: BROWSER=safari8 DISABLE_WEBSOCKET_TESTS=true npm run test:integration:ci
      - run: BROWSER=ie11_win DISABLE_WEBSOCKET_TESTS=true npm run test:integration:ci
workflows:
  version: 2
  test-workflow:
    jobs:
#      - go-test
#      - ts-test
#      - lint
      - pre-build-browser-tests
      - browser-tests:
          pre-steps:
            - checkout
            - run: sudo apt-get install moreutils
            - run: echo 127.0.0.1 testhost | sudo tee -a /etc/hosts
            - run: echo 127.0.0.1 corshost | sudo tee -a /etc/hosts
            - run:
                command: |
                  set +e
                  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.33.5/install.sh | bash
                  export NVM_DIR="/home/circleci/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                  nvm install
                  echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
                  echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
            - run: npm install
          requires:
            - pre-build-browser-tests