version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/golang:1.15.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    environment:
      PROTOTOOL_VER: 1.7.0
    working_directory: /go/src/github.com/improbable-eng/grpc-web


jobs:
  pre-build-browser-tests:
    executor: my-executor
    steps:
      - checkout
      - run: sudo apt-get install unzip
      - run: . ./install-prototool.sh
      - run: go get -u golang.org/x/tools/cmd/goimports
      - run: go get -u github.com/robertkrimen/godocdown/godocdown
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure
      - run: go install ./vendor/github.com/golang/protobuf/protoc-gen-go
      - run: export PATH=/home/travis/gopath/src/github.com/improbable-eng/grpc-web/protobuf/bin:$PATH
      - run:
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.33.5/install.sh | bash
            export NVM_DIR="/home/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install
            echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
            echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
      - run: npm install
      - run:
          name: Pre-Build Integration Test
          command: npm run build:integration
      - persist_to_workspace:
          root: /go/src/github.com/improbable-eng/grpc-web
          paths:
            - integration_test
  browser-tests:
    executor: my-executor
    parallelism: 4
    steps:
      - attach_workspace:
          at: /go/src/github.com/improbable-eng/grpc-web
      - run: << parameters.browser-params >> npm run test:integration:ci
workflows:
  version: 2
  test-workflow:
    jobs:
#      - go-test
#      - ts-test
#      - lint
      - pre-build-browser-tests
      - browser-tests:
          matrix:
            parameters:
              browser-params:
#                - BROWSER=nodejs
                - BROWSER=firefox80_win
                - BROWSER=firefox39_win
                - BROWSER=firefox38_win
                - BROWSER=firefox21_win
                - BROWSER=chrome_85
                - BROWSER=chrome_52
                - BROWSER=chrome_43
                - BROWSER=chrome_42
                - BROWSER=edge85_win
                - BROWSER=edge16_win
                - BROWSER=safari13_1 DISABLE_WEBSOCKET_TESTS=true
                - BROWSER=safari12_1 DISABLE_WEBSOCKET_TESTS=true
                - BROWSER=safari11_1 DISABLE_WEBSOCKET_TESTS=true
                - BROWSER=safari10_1 DISABLE_WEBSOCKET_TESTS=true
                - BROWSER=safari9_1 DISABLE_WEBSOCKET_TESTS=true
                - BROWSER=safari8 DISABLE_WEBSOCKET_TESTS=true
                - BROWSER=ie11_win DISABLE_WEBSOCKET_TESTS=true
          pre-steps:
            - checkout
            - run: sudo apt-get install moreutils
            - run: echo 127.0.0.1 testhost | sudo tee -a /etc/hosts
            - run: echo 127.0.0.1 corshost | sudo tee -a /etc/hosts
            - run:
                command: |
                  set +e
                  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.33.5/install.sh | bash
                  export NVM_DIR="/home/circleci/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                  nvm install
                  echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
                  echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
            - run: npm install
          requires:
            - pre-build-browser-tests